name: CWS CI

# Triggers the workflow on push or pull request
#on: [push, pull_request]
on: [push]

jobs:

  build-cws:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven
      - name: Download Logstash
        uses: carlosperate/download-file-action@v1
        with:
          file-url: https://artifacts.elastic.co/downloads/logstash/logstash-oss-7.16.2-windows-x86_64.zip
          file-name: logstash-7.16.2.zip
          location: install/logging/
      - name: Check for Logstash
        run: |
          cd install/logging/
          ls -l
      - name: Elasticsearch Setup
        run: |
          cd install/docker/es-only
          docker-compose up -d
      - name: Set up CWS database using Docker
        run: docker run -d -p 3306:3306 -e MYSQL_DATABASE=cws_dev -e MYSQL_ROOT_PASSWORD=rootpw --name mdb103 mariadb:10.3
      - name: Set up Elasticsearch
        run: |
          cd install/docker/es-only
          docker-compose up -d
      - name: Show Docker containers
        run: |
          sleep 5s
          docker ps -a
      - name: Stop CWS
        run: |
          chmod +x stop_dev.sh
          ./stop_dev.sh
      - name: Run CWS
        run:  |
          cd ci
          chmod +x run_ci.sh
          ./run_ci.sh
        shell: bash


  run-tests:

    runs-on: ubuntu-latest

    needs: build-cws

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven
      - name: CWS Unit and Integration Test Run
        run: |
          chmod +x test.sh
          ./test.sh
