name: CWS CI

# Triggers the workflow on push or pull request
#on: [push, pull_request]
on: [push]

jobs:

  build-cws:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven
      - name: create open-source certs
        run: |
          cd cws-certs
          chmod +x generate-certs.sh
          ./generate-certs.sh
      - name: Download Logstash
        uses: carlosperate/download-file-action@v1
        with:
          file-url: https://artifacts.elastic.co/downloads/logstash/logstash-oss-7.16.2-windows-x86_64.zip
          file-name: logstash-7.16.2.zip
          location: install/logging/
      - name: Check for Logstash
        run: |
          cd install/logging/
          ls -l
      - name: Elasticsearch Setup
        run: |
          cd install/docker/es-only
          docker-compose up -d
      - name: Set up CWS database using Docker
        run: docker run -d -p 3306:3306 -e MYSQL_DATABASE=cws_dev -e MYSQL_ROOT_PASSWORD=rootpw --name mdb103 mariadb:10.3
      - name: Set up Elasticsearch
        run: |
          cd install/docker/es-only
          docker-compose up -d
      - name: Show Docker containers
        run: |
          sleep 5s
          docker ps -a
      - name: Stop CWS
        run: |
          chmod +x stop_dev.sh
          ./stop_dev.sh
      - name: Run CWS
        run:  |
          cd ci
          chmod +x run_ci.sh
          ./run_ci.sh
        shell: bash
      - name: Show CWS Log
        run: |
         cd dist/console-only/cws/server/apache-tomcat-9.0.33/logs
         ls -al
      - name: Run Unit and Integration Tests
        run: |
          chmod +x test.sh
          ./test.sh
        shell: bash
      - name: Move Jacoco Report
        run: |
          cd jacoco-reports/aggregate
          cp index.html ../../
      - name: Send Jacoco Report
        uses: dawidd6/action-send-mail@v3
        with:
          # Required mail server address:
          server_address: ${{secrets.MAIL_SERVER}}
          # Required mail server port:
          server_port: 465
          # Required mail subject:
          subject: Jacoco Report
          # Required recipients' addresses:
          to: ${{secrets.MAIL_ADDRESS}}
          # Required sender full name (address can be skipped):
          from: CI GitHub Actions
          # Optional whether this connection use TLS (default is true if server_port is 465)
          # secure: true
          # Optional HTML body read from file:
          html_body: file://index.html
          # Optional carbon copy recipients:
          cc: ronnyfray@gmail.com
          # Optional unsigned/invalid certificates allowance:
          ignore_cert: true


  #run-tests:

    #runs-on: ubuntu-latest

    #needs: build-cws

    #steps:
      #- uses: actions/checkout@v3
      #- name: Set up JDK 8
        #uses: actions/setup-java@v3
        #with:
          #java-version: '8'
          #distribution: 'temurin'
          #cache: maven
      #- name: CWS Unit and Integration Test Run
        #run: |
          #chmod +x test.sh
          #./test.sh
