# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

# Triggers the workflow on push or pull request
on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    - name: Set up CWS database using Docker
      run: docker run -d -p 3306:3306 -e MYSQL_DATABASE=cws_dev -e MYSQL_ROOT_PASSWORD=rootpw -e TZ=America/Los_Angeles --name mdb103 mariadb:10.3
    - name: Download Logstash
      uses: carlosperate/download-file-action@v1
      with:
        file-url: https://artifacts.elastic.co/downloads/logstash/logstash-oss-7.16.2-windows-x86_64.zip
        file-name: logstash-7.16.2.zip
        location: install/logging/
    - name: Check for Logstash
      run: cd install/logging/
    - run: ls -l
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Directory
      run: pwd
    - name: change test.sh permission
      run: chmod +x test.sh
    - name: CWS Unit and Integration Test Run
      run: ./test.sh
      #run: git update-index --chmod +x ./test.sh

