# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

# Triggers the workflow on push or pull request
#on: [push, pull_request]
on: [push]

env:
  INTERNET_TYPE: 0
  HOSTNAME: "localhost"
  SECURITY: "camunda"
  DB_TYPE: mariadb
  DB_HOST: 127.0.0.1
  DB_NAME: cws_dev
  DB_USER: root
  DB_PASS: rootpw
  DB_PORT: 3306
  ES_PROTOCOL: "http"
  ES_HOST: "localhost"
  ES_PORT: 9200
  ES_USE_AUTH: n
  ES_USERNAME: "na"
  ES_PASSWORD: "na"
  NUM_WORKERS: 1
  WORKER_ABANDONED_DAYS: 1
  USER: cwsci
  CLOUD: n
  EMAIL_LIST: "/"
  ADMIN_FIRST: "/"
  ADMIN_LAST: "/"
  ADMIN_EMAIL: "/"

jobs:

  #build-elasticsearch:

    #runs-on: ubuntu-latest

    #steps:
      #- uses: actions/checkout@v3
      #- name: Set up Elasticsearch
        #run: |
          #cd install/docker/es-only
          #docker-compose up

  #build-database:

    #runs-on: ubuntu-latest

    #steps:
    #- name: Set up CWS database using Docker
      #run: docker run -d -p 3306:3306 -e MYSQL_DATABASE=cws_dev -e MYSQL_ROOT_PASSWORD=rootpw -e TZ=America/Los_Angeles --name mdb103 mariadb:10.3

  build-cws:

    runs-on: ubuntu-latest

    #needs: build-database


    services:
      cws-es:
        image: elasticsearch:7.16.2
        ports:
          - 9200:9200
          - 9300:9300
        options: >-
          --health-interval 5s
          --health-timeout 2s
          --health-retires 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    - name: Set up CWS database using Docker
      run: docker run -d -p 3306:3306 -e MYSQL_DATABASE=cws_dev -e MYSQL_ROOT_PASSWORD=rootpw -e TZ=America/Los_Angeles --name mdb103 mariadb:10.3
    - name: Download Logstash
      uses: carlosperate/download-file-action@v1
      with:
        file-url: https://artifacts.elastic.co/downloads/logstash/logstash-oss-7.16.2-windows-x86_64.zip
        file-name: logstash-7.16.2.zip
        location: install/logging/
    - name: Check for Logstash
      run:  |
        cd install/logging/
        ls -l
    #- name: Build with Maven
      #run: mvn -B package --file pom.xml
    - run: chmod +x stop_dev.sh
    - run: ./stop_dev.sh
    - name: run dev.sh
      run:  |
        chmod +x dev.sh
        ./dev.sh `pwd` ${USER} ${DB_TYPE} ${DB_HOST} ${DB_PORT} ${DB_NAME} ${DB_USER} ${DB_PASS} ${ES_PROTOCOL} ${ES_HOST} ${ES_PORT} ${ES_USE_AUTH} ${ES_USERNAME} ${ES_PASSWORD} ${CLOUD} ${SECURITY} ${HOSTNAME} ${EMAIL_LIST} ${ADMIN_FIRST} ${ADMIN_LAST} ${ADMIN_EMAIL} ${NUM_WORKERS} ${WORKER_ABANDONED_DAYS}
      shell: bash

  run-tests:

    runs-on: ubuntu-latest

    needs: build-cws

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven
      - name: change test.sh permission
        run: chmod +x test.sh
      - name: CWS Unit and Integration Test Run
        run: ./test.sh
